# Generated by Django 3.2 on 2021-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
